version: '3.1'

services:
  postgres:
    image: postgres
    container_name: graphql_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: graphql
      POSTGRES_USER: graphql
      POSTGRES_PASSWORD: 123456
    networks:
      - aplication-network

  app:
    build: .
    container_name: graphql_app
    depends_on:
      - postgres
    ports:
      - "3333:3333"
    environment:
      DB_HOST: postgres
    volumes:
      - .:/var/www
    networks:
      - aplication-network

networks:
  aplication-network:
    driver: bridge
